[2024-11-08T22:56:37.640+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T22:56:37.658+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transformacao_dolar_silver.silver_cotacao_dolar_spark scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T22:56:37.668+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transformacao_dolar_silver.silver_cotacao_dolar_spark scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T22:56:37.669+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-08T22:56:37.688+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): silver_cotacao_dolar_spark> on 2024-11-07 00:00:00+00:00
[2024-11-08T22:56:37.695+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=462) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-08T22:56:37.697+0000] {standard_task_runner.py:72} INFO - Started process 463 to run task
[2024-11-08T22:56:37.696+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transformacao_dolar_silver', 'silver_cotacao_dolar_spark', 'scheduled__2024-11-07T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/transformation.py', '--cfg-path', '/tmp/tmpqdgni14p']
[2024-11-08T22:56:37.698+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask silver_cotacao_dolar_spark
[2024-11-08T22:56:37.745+0000] {task_command.py:467} INFO - Running <TaskInstance: transformacao_dolar_silver.silver_cotacao_dolar_spark scheduled__2024-11-07T00:00:00+00:00 [running]> on host f7c2f8c61729
[2024-11-08T22:56:37.824+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mateus Copi' AIRFLOW_CTX_DAG_ID='transformacao_dolar_silver' AIRFLOW_CTX_TASK_ID='silver_cotacao_dolar_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-07T00:00:00+00:00'
[2024-11-08T22:56:37.825+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T22:56:37.850+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-11-08T22:56:37.851+0000] {spark_submit.py:327} ERROR - Failed to decode base64 keytab: Incorrect padding
[2024-11-08T22:56:37.852+0000] {spark_submit.py:304} INFO - Could not load connection string spark_default, defaulting to spark://master:7077
[2024-11-08T22:56:37.854+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://master:7077 --principal *** --name arrow-spark --deploy-mode client /opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py
[2024-11-08T22:56:41.472+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SparkContext: Running Spark version 3.5.3
[2024-11-08T22:56:41.478+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-08T22:56:41.479+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SparkContext: Java version 17.0.13
[2024-11-08T22:56:41.569+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-08T22:56:41.657+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceUtils: ==============================================================
[2024-11-08T22:56:41.657+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-08T22:56:41.658+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceUtils: ==============================================================
[2024-11-08T22:56:41.658+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SparkContext: Submitted application: spark-cotacao-dolar-siver-minio
[2024-11-08T22:56:41.681+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-08T22:56:41.693+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceProfile: Limiting resource is cpu
[2024-11-08T22:56:41.694+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-08T22:56:41.757+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SecurityManager: Changing view acls to: default
[2024-11-08T22:56:41.757+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SecurityManager: Changing modify acls to: default
[2024-11-08T22:56:41.758+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SecurityManager: Changing view acls groups to:
[2024-11-08T22:56:41.759+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SecurityManager: Changing modify acls groups to:
[2024-11-08T22:56:41.760+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-11-08T22:56:41.955+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO Utils: Successfully started service 'sparkDriver' on port 42111.
[2024-11-08T22:56:41.982+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:41 INFO SparkEnv: Registering MapOutputTracker
[2024-11-08T22:56:42.031+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-08T22:56:42.048+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-08T22:56:42.049+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-08T22:56:42.054+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-08T22:56:42.074+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-bb04f88f-2eca-42ca-b0de-c1ac780f865f
[2024-11-08T22:56:42.091+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-08T22:56:42.107+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-08T22:56:42.259+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-08T22:56:42.325+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-11-08T22:56:42.480+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-08T22:56:42.593+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.6:7077 after 76 ms (0 ms spent in bootstraps)
[2024-11-08T22:56:42.738+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241108225642-0003
[2024-11-08T22:56:42.739+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241108225642-0003/0 on worker-20241108214035-172.18.0.2-33781 (172.18.0.2:33781) with 1 core(s)
[2024-11-08T22:56:42.741+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO StandaloneSchedulerBackend: Granted executor ID app-20241108225642-0003/0 on hostPort 172.18.0.2:33781 with 1 core(s), 1024.0 MiB RAM
[2024-11-08T22:56:42.761+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37847.
[2024-11-08T22:56:42.762+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO NettyBlockTransferService: Server created on f7c2f8c61729:37847
[2024-11-08T22:56:42.769+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-08T22:56:42.788+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f7c2f8c61729, 37847, None)
[2024-11-08T22:56:42.797+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManagerMasterEndpoint: Registering block manager f7c2f8c61729:37847 with 434.4 MiB RAM, BlockManagerId(driver, f7c2f8c61729, 37847, None)
[2024-11-08T22:56:42.801+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f7c2f8c61729, 37847, None)
[2024-11-08T22:56:42.804+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f7c2f8c61729, 37847, None)
[2024-11-08T22:56:42.999+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:42 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241108225642-0003/0 is now RUNNING
[2024-11-08T22:56:43.147+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:43 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-08T22:56:44.245+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:44 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-08T22:56:44.255+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:44 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2024-11-08T22:56:45.989+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:45 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.2:48594) with ID 0,  ResourceProfileId 0
[2024-11-08T22:56:46.238+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.2:43939 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.2, 43939, None)
[2024-11-08T22:56:46.728+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-08T22:56:46.730+0000] {spark_submit.py:634} INFO - File "/opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py", line 64, in <module>
[2024-11-08T22:56:46.730+0000] {spark_submit.py:634} INFO - main()
[2024-11-08T22:56:46.731+0000] {spark_submit.py:634} INFO - File "/opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py", line 60, in main
[2024-11-08T22:56:46.731+0000] {spark_submit.py:634} INFO - df.write.format('parquet').mode('overwrite').save(f'{bucket}')
[2024-11-08T22:56:46.732+0000] {spark_submit.py:634} INFO - File "/opt/***/spark/spark-3.5.3-bin-hadoop3/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1463, in save
[2024-11-08T22:56:46.732+0000] {spark_submit.py:634} INFO - File "/opt/***/spark/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-08T22:56:46.732+0000] {spark_submit.py:634} INFO - File "/opt/***/spark/spark-3.5.3-bin-hadoop3/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-08T22:56:46.733+0000] {spark_submit.py:634} INFO - File "/opt/***/spark/spark-3.5.3-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-08T22:56:46.734+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o58.save.
[2024-11-08T22:56:46.735+0000] {spark_submit.py:634} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2024-11-08T22:56:46.739+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2024-11-08T22:56:46.740+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2024-11-08T22:56:46.740+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2024-11-08T22:56:46.741+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2024-11-08T22:56:46.741+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2024-11-08T22:56:46.742+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2024-11-08T22:56:46.742+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2024-11-08T22:56:46.743+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2024-11-08T22:56:46.743+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:454)
[2024-11-08T22:56:46.744+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:530)
[2024-11-08T22:56:46.744+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2024-11-08T22:56:46.745+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2024-11-08T22:56:46.745+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
[2024-11-08T22:56:46.746+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-08T22:56:46.746+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-08T22:56:46.747+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-08T22:56:46.747+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-08T22:56:46.748+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-08T22:56:46.749+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T22:56:46.749+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-08T22:56:46.750+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-08T22:56:46.750+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-08T22:56:46.752+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T22:56:46.753+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T22:56:46.753+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-08T22:56:46.754+0000] {spark_submit.py:634} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2024-11-08T22:56:46.754+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2024-11-08T22:56:46.755+0000] {spark_submit.py:634} INFO - at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2024-11-08T22:56:46.756+0000] {spark_submit.py:634} INFO - ... 24 more
[2024-11-08T22:56:46.756+0000] {spark_submit.py:634} INFO - 
[2024-11-08T22:56:46.907+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO SparkContext: Invoking stop() from shutdown hook
[2024-11-08T22:56:46.908+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-08T22:56:46.918+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO SparkUI: Stopped Spark web UI at http://f7c2f8c61729:4040
[2024-11-08T22:56:46.923+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-08T22:56:46.924+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-08T22:56:46.965+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-08T22:56:46.984+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO MemoryStore: MemoryStore cleared
[2024-11-08T22:56:46.985+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO BlockManager: BlockManager stopped
[2024-11-08T22:56:46.995+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:46 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-08T22:56:47.008+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-08T22:56:47.022+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO SparkContext: Successfully stopped SparkContext
[2024-11-08T22:56:47.022+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO ShutdownHookManager: Shutdown hook called
[2024-11-08T22:56:47.022+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO ShutdownHookManager: Deleting directory /tmp/spark-df240102-45c0-4ad0-bc34-94a5e179fe4b/pyspark-70f409ab-7612-42db-8197-da73e2be38fb
[2024-11-08T22:56:47.028+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO ShutdownHookManager: Deleting directory /tmp/spark-df240102-45c0-4ad0-bc34-94a5e179fe4b
[2024-11-08T22:56:47.033+0000] {spark_submit.py:634} INFO - 24/11/08 22:56:47 INFO ShutdownHookManager: Deleting directory /tmp/spark-254c1b17-d783-4d3c-a2f4-8dcf406686a9
[2024-11-08T22:56:47.082+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:7077 --principal *** --name arrow-spark --deploy-mode client /opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py. Error code is: 1.
[2024-11-08T22:56:47.087+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=transformacao_dolar_silver, task_id=silver_cotacao_dolar_spark, run_id=scheduled__2024-11-07T00:00:00+00:00, execution_date=20241107T000000, start_date=20241108T225637, end_date=20241108T225647
[2024-11-08T22:56:47.099+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T22:56:47.100+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 94 for task silver_cotacao_dolar_spark (Cannot execute: spark-submit --master spark://master:7077 --principal *** --name arrow-spark --deploy-mode client /opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py. Error code is: 1.; 463)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:7077 --principal *** --name arrow-spark --deploy-mode client /opt/***/scripts/transformacoes/cotacao_dolar/cotacao_dolar_silver.py. Error code is: 1.
[2024-11-08T22:56:47.128+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-08T22:56:47.149+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T22:56:47.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
